#!/usr/bin/env node
//
// Wrapper to call the correct binary, based on the platform.
//
const spawn = require('child_process').spawn;
const os = require('os');
const path = require('path');

let binary;
if (os.platform() === 'darwin') {
	binary = 'ninja-mac';
} else if (os.platform() === 'win32') {
	binary = 'ninja-win.exe';
} else {
	binary = 'ninja-linux';
}

let cmd = path.join(__dirname, 'binaries', binary);
let args = process.argv.slice(2);
let ps = spawn(`"${cmd}"`, args, {
	shell: true,
	stdio: 'inherit'
});
ps.on('error', function(code) {
	process.stderr.write('Unable to spawn ninja\n');
	process.exit(255); // use a code not used by Ninja
});
ps.on('close', function(code) {
	process.exit(code);
});
